name: Deploy GitHub Pages
on:
  push:
    branches: [ main ]  # 监听 main 分支推送
jobs:
  build-deploy:
    runs-on: self-hosted  # 关键！指定企业自托管运行器
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Deploy
      uses: actions/deploy-pages@v2
